# Generated by Django 5.2 on 2025-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_owner_ownerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
